### ISSUE TITLE
Heating / Cooling design temperatures

### ISSUE THREAD

**Issue by alemenchaca** [mostaphaRoudsari/epwmap#1]
It's been a couple of times already where I need to quickly look up heating / cooling design temperatures of different cities, hoping epwmap can give me that info without having to download the files... Any chance that info could be added to the climate summary when hovering over a weather file location?

**Comment by chriswmackey** [comment]
@alemenchaca ,
 @mostaphaRoudsari just moved the github of EPWmap to the official [Ladybug Tools Organization](https://github.com/ladybug-tools) page, so I am continuing this issue here:
https://github.com/ladybug-tools/epwmap/issues/18

**Comment by mostaphaRoudsari** [comment]
I close this in favor of ladybug-tools/epwmap#18
