### ISSUE TITLE
Move legend to right-top with a white background

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/epwmap#13]
https://twitter.com/arch_laboratory/status/572858640211681282

Having horizontal legends are not the best approach, considering that we will have a couple of other types added to the list soon. I think an alternative option is to have it up right under Map|Satellites.

**Comment by ksobon** [comment]
Hey. I dont mind it being vertical. Adding a white background behind it will fix my issue. Thanks!

**Comment by mostaphaRoudsari** [comment]
Done!
![image](https://cloud.githubusercontent.com/assets/2915573/6538930/d7423214-c436-11e4-88d5-dc87339d1876.png)
