### ISSUE TITLE
Add an Option to Copy the ZIP file link to clipboard

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/epwmap#14]
Copying the ZIP file link to the clipboard is pretty essential for my workflow with the "Import EPW and STAT" component.  Are there plans in the works for this at some point?

**Comment by mostaphaRoudsari** [comment]
Now there will be! I think I will assign it to right click.

**Comment by mostaphaRoudsari** [comment]
Right click, ctrl+c, enter!

![image](https://cloud.githubusercontent.com/assets/2915573/6538911/a59519c0-c436-11e4-8978-4b7d7d9f4ef2.png)
